# Use postgres/example user/password credentials
version: '3.7'

services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      - db_volume:/var/lib/postgresql/data
  todo:
    depends_on:
      - database
    build: .
    ports:
      - 80:80
    volumes:
      - ./server:/opt/todo
  test:
    build:
      context: .
      dockerfile: test.dockerfile
    volumes:
      - ./server:/opt/todo
  web:
    build:
      context: .
      dockerfile: web.dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./web:/opt/todo

volumes:
  db_volume:
